# Site settings
title: Upsome
email: support@feelingsunday.com
description: > # this means to ignore newlines until "baseurl:"
  Upsome - Follow your heart
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.feelingsunday.com" # the base hostname & protocol for your site

timezone: Asia/Seoul
markdown: redcarpet
pygments: true

paginate: 5
paginate_path: "/blog/page:num/"

navigation:
- text: About
  url: /about/
- text: Blog
  url: /blog/
- text: Contact
  url: /contact/
