# Site settings
title: Upsome
email: support@feelingsunday.com
description: > # this means to ignore newlines until "baseurl:"
  Upsome - Follow your heart
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.feelingsunday.com" # the base hostname & protocol for your site

timezone: America/Los_Angeles
markdown: redcarpet
pygments: true

paginate: 5
paginate_path: "/blog/page:num/"

navigation:
  - text: About
    url: /about/
    indexUrl: /about/index.html
  - text: Blog
    url: /blog/
    indexUrl: /blog/index.html
  - text: Contact
    url: /contact/
    indexUrl: /contact/index.html
